### ISSUE TITLE
a noob prolem

### ISSUE THREAD

**Issue by Robot-1x** [c2huc2hu/jps#1]
I have tried your code and found some maps were suitable and others not. Those failed report:'' if field [cur_x] [cur_y] == UNINITIALIZED:  IndexError: list index out of range ''.

**Comment by c2huc2hu** [comment]
You haven't provided enough information to reproduce the problem, so I'll give you some tips instead: 

1) Make sure that `field[start_x][start_y]` is in bounds. You might have the coordinates backward. 
2) Make sure you're padding the field with obstacles around the outside. I don't do bound detection. You can use the `generate_field` function to do this automatically (although it overwrites the outer layer, idk why I did that :/ )

**Comment by Robot-1x** [comment]
Thank you. I've retried as you mentioned and it works well. Because I've revised the code and  it could not make sure the outside edges of map with obstacles.

**Comment by c2huc2hu** [comment]
Yeah, this code is a couple years old and definitely needs some refactoring. Glad I could help!
